@@ -0,0 +1,33 @@
.center {
  text-align: center;
  align-items: center;
}

.padding {
  padding: 20px;
}

.orangeBG {
  background-color: orange;
}

.largepadding {
  padding-top: 100px;
  padding-bottom: 100px;
}

.fontwhite {
  color: white;
}

h1{
  font-family: 'Roboto Condensed', sans-serif;
  font-weight: 700;
}

h3{
  font-family: 'Roboto Condensed', sans-serif;
}
h4{
  font-family: 'Roboto Condensed', sans-serif;
}

theme: jekyll-theme-modernist